release-argus/Argus

config/defaults.go, service/query.go, service/types.go
Fixes cases where a patch for an older major/minor is released after the current latest major/minor. We now sort all the tag_names and pick the latest when semver
=> bug(query): sort github tag_names when semver

config/config_test.go, config/defaults.go, config/save.go, notifiers/shoutrrr/gets.go, notifiers/shoutrrr/init.go, notifiers/shoutrrr/shoutrrr.go, notifiers/shoutrrr/shoutrrr_test.go, notifiers/shoutrrr/types.go, notifiers/shoutrrr/verify.go, web/api/types/argus.go
e.g. `service.notify.something` would be removed when saving if it was empty (`{}`), meaning it's getting all its params etc from `notify.something`
(the code I wrote to remove empty mappings, e.g. `defaults: {}` was set to ignore `service.notify.something: {}`, but since 'options','url_fields','params' were pointers, they would still be encoded as when empty, they wouldn't be their default state (nil). So my code would see all of those as empty maps (e.g. `params: {}`) and remove them. It would then remove the parent as it wasn't mapping to anything anymore)
Fixed this by not making `params` etc a pointer, so they'll be in their default state when empty and won't be encoded when saved)
fixes https://github.com/release-argus/Argus/issues/75
=> fix(saving): empty `service.notify.name`s were removed

web/api/types/argus.go, web/api/v1/websocket.go, web/ui/react-app/src/types/config.tsx, webhook/github.go, webhook/init.go, webhook/types.go
In `adnanh/webhook`:
```yaml
- id: something
execute-command: SOMETHING.SH
pass-arguments-to-command:
- source: header
name: CUSTOM_HEADER_NAME
```
in `Argus` config.yml:
```yaml
webhook:
some_name:
custom_headers:
CUSTOM_HEADER_NAME: hello123
```
would execute ["SOMETHING.SH" "hello123"]
=> feat(webhook): support for custom headers

service/verify.go, webhook/gitlab.go, webhook/init.go, webhook/verify.go
Add basic Support for GitLab Webhooks/Triggers.
[docs.gitlab.com/15.0/ee/ci/triggers](https://docs.gitlab.com/15.0/ee/ci/triggers/)
=> feat(webhook): add type gitlab

commands/announce.go, commands/announce_test.go, commands/commands.go, commands/commands_test.go, commands/init.go, commands/init_test.go, commands/types.go, config/init.go, service/init.go, service/service_test.go, service/status.go, service/status/status.go, service/types.go, service/verify.go, web/api/v1/websocket.go, webhook/github.go, webhook/github_test.go, webhook/gitlab_test.go, webhook/init.go, webhook/init_test.go, webhook/types.go
version = 1.2.3
```yaml
webhook:
name:
url: https://example.com/{{ version }}
```
to use `https://example.com/1.2.3`
```yaml
webhook:
name:
type: github
custom_headers:
version: '{{ version }}'
```
to give the webhook a header of `version: 1.2.3`
```yaml
command:
- ["something.sh", "{{ version }}"]
```
should do `something.sh 1.2.3`
=> feat(commands,webhook): pass version to webhook or command

notifiers/shoutrrr/shoutrrr.go, notifiers/shoutrrr/shoutrrr_test.go, testing/shoutrrr.go, utils/template.go
allows use of things like `{{ version }}` and `{{ service_id }}` in notify params
=> feat(notify): jinja templating on params

utils/help_test.go, utils/lists.go, utils/lists_test.go, utils/log.go, utils/log_test.go, utils/regex_test.go, utils/template_test.go, utils/util_test.go
coverage decrease from removed lines
```
- | LevelStr   string // The string value of Level (ERROR/WARN/INFO/VERBOSE/DEBUG)
- | l.LevelStr = level
```
was being set but never used
=> test(utils): table-driven tests

config/ordering.go, config/ordering_test.go
was only using `X.options.active`, but before the service had `X.active` converted to `X.options.active`.
=> fix(config): use both converted and unconverted `active` vars

config/settings.go, web/api/v1/api.go, web/api/v1/http.go, web/api/v1/http_test.go
Basic auth support inside Argus
=> feat(web): basic auth

.github/workflows/codecov.yml, service/latest_version/filters/docker.go, service/latest_version/filters/docker_test.go, service/latest_version/query.go
Wasn't ever using the creds (if provided) for DockerHub/Quay lookups and was requiring creds for Quay even though they're not always necessary
=> fix(require): use auth for Docker lookups

service/deployed_version/deployed_version.go, service/latest_version/query.go
https://github.com/release-argus/Argus/issues/153
wasn't closing latest/deployed version connections with
> defer resp.Body.close
=> fix(service): close latest/deployed version http connections

service/deployed_version/deployed_version.go, service/latest_version/filters/docker.go, service/latest_version/query.go, web/api/v1/http.go, web/web.go, webhook/init.go
> A significant difference between HTTP/1.1 and earlier versions of HTTP is that persistent connections are the default behavior of any HTTP connection.
Inform the server that the client wants to close the connection after the transaction is complete. This can be done by setting the [Connection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection) header
[source](http://craigwickesser.com/2015/01/golang-http-to-many-open-files/)
[fix?](https://github.com/release-argus/Argus/issues/153#issuecomment-1245847113)
=> fix(service): use `Connection` header on HTTP requests

utils/util.go, web/api/v1/help_test.go, web/api/v1/websocket.go, webhook/announce_test.go, webhook/headers.go, webhook/headers_test.go, webhook/help_test.go, webhook/init_test.go, webhook/send_test.go, webhook/types.go, webhook/verify.go, webhook/verify_test.go
`custom_headers` for WebHook `ABC` wasn't using headers defined in `webhook.ABC.custom_headers` or `defaults.webhook.custom_headers`. It'd only use those in `service.XYZ.webhook.ABC.custom_headers`
=> fix(webhook): `custom_headers` from main/defaults

notifiers/shoutrrr/shoutrrr.go, notifiers/shoutrrr/shoutrrr_test.go, notifiers/shoutrrr/verify.go, testing/shoutrrr.go
shoutrrr wants `matrix://:password@...` not `matrix://password@...`
fixes: https://github.com/release-argus/Argus/issues/193
=> fix(notify): get access_token `password`s working for matrix

notifiers/shoutrrr/verify.go, notifiers/shoutrrr/verify_test.go
`.Locate` logs in on Matrix types. Skip the Locate for them to help against login rate-limiting
```
2023/01/11 20:25:15 DEBUG: 1/109 org/repo1 Init
2023/01/11 20:25:15 DEBUG: 2/109 org/repo2 Init
2023/01/11 20:25:15 DEBUG: 3/109 org/repo3 Init
2023/01/11 20:25:15 DEBUG: 4/109 org/repo4 Init
2023/01/11 20:25:15 DEBUG: 5/109 org/repo5 Init
...
org/repo1:
notify:
matrix:
^ failed to log in: Too Many Requests
org/repo2:
notify:
matrix:
^ failed to log in: Too Many Requests
org/repo3:
notify:
matrix:
^ failed to log in: Too Many Requests
org/repo4:
notify:
matrix:
^ failed to log in: Too Many Requests
org/repo5:
notify:
matrix:
^ failed to log in: Too Many Requests
```
=> fix(notify): don't login to matrix to verify (could rate-limit fail)

Dockerfile
According to the official best practices guidelines outlined in the following document:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
The official Debian/Ubuntu images have been configured to do apt-get clean automatically. Consequently, performing another `apt-get clean` is unnecessary. Instead, it is crucial to clear the cache for the index file by executing this command: `rm -rf /var/lib/apt/lists/*`.
The image size before and after the change for reference:
```
REPOSITORY       TAG                 IMAGE ID       CREATED             SIZE
after            latest              40ad44683af3   55 minutes ago      116MB
before           latest              ce25232e7649   About an hour ago   134MB
```
=> Clean up Docker image apt files the right way

config/defaults.go, config/defaults_test.go, config/settings.go, config/settings_test.go, config/verify.go, package-lock.json, package.json, web/api/v1/http.go, web/api/v1/http_test.go, web/api/v1/util.go, web/api/v1/util_test.go
* sha256 the username/password and store in the config as 'h__HASH'
* basic_auth removed if both username and password are empty
* favicon removed if both svg and png overrides are empty
=> feat(config): hash `basic_auth.(username|password)` locally

config/settings.go, config/settings_test.go, service/deployed_version/query_test.go, web/help_test.go, webhook/headers.go, webhook/headers_test.go
Missed these in c5d5532
* settings.web.basic_auth.username
* settings.web.basic_auth.password
* webhook.*.custom_headers.*.key
* webhook.*.custom_headers.*.value
=> feat(config): more env var support

cmd/argus/yaml_help_test.go, config/help_test.go, config/init.go, config/init_test.go, config/ordering.go, config/save_test.go, config/yaml_help_test.go, package-lock.json, package.json
and empty services
```yaml
service:
emptyService:
```
Was causing kernel panics because it looks for X leading spaces for each service in the `service:` section. `# commentedOutService` unmarshals to "" and the service is nil, so `.Init` and other functions on it panic because of nil-pointers
=> fix(config): handle commented out services

web/ui/package-lock.json, web/ui/react-app/src/components/modals/service-edit/notify-types/extra/ntfy/actions.tsx
* was getting an uncaught TypeError as we were iterating undefined
=> fix(web): ntfy, default fieldValues for actions

web/ui/react-app/src/components/approvals/service-info.tsx, web/ui/react-app/src/utils/is-empty-or-null.tsx, web/ui/react-app/src/utils/query-params.tsx
```js
if (oldObj === undefined) return newObj;
const keys = Object.keys(oldObj).concat(Object.keys(newObj));
```
If 'oldObj' is null, it would get past the undefined check, but crash on Object.keys of null
fixes #514
=> fix(ui): handle null oldObj in deepDiff to prevent refresh failure

web/ui/react-app/src/components/modals/service-edit/version-with-refresh.tsx, web/ui/react-app/src/utils/is-empty.tsx
`convertedOriginal` wasn't depending on the service data, so with the move from placeholder skeletons, to empty form, having the serviceID doesn't mean it can get the data. So the diff on refresh was comparing the form data with null, and so always sent the current form values as query params. This makes the refresh only happen on your browser session and does not trigger a version change in the backend.
=> fix(ui): have VersionWithRefresh depend on original data

Dockerfile
With this, the entrypoint runs as 'argus:argus', so it wouldn't have permissions to change the UID/GID when ARGUS_UID/ARGUS_GID are set. This breaks upgrades as the file would be owned by a different user, so 911:911 wouldn't be able to write to the db.
fixes #519
=> fix(docker): remove hardcoded USER to restore custom UID/GID support

cmd/argus/main.go, cmd/argus/main_test.go, command/help_test.go, config/help_test.go, config/init.go, config/settings_test.go, db/help_test.go, notify/shoutrrr/help_test.go, service/deployed_version/help_test.go, service/help_test.go, service/init_test.go, service/latest_version/filter/help_test.go, service/latest_version/help_test.go, service/latest_version/init_test.go, service/latest_version/types/github/help_test.go, service/latest_version/types/web/help_test.go, test/log/log.go, test/log/log_test.go, testing/help_test.go, util/log/log.go, web/api/v1/help_test.go, web/api/v1/http_test.go, web/help_test.go, web/ui/package-lock.json, webhook/help_test.go
Wasn't initialising the logger before the first possible log.
Builds on #528. (Was keeping the log level at `ERROR` until after `config.Load`, meaning the Debug logs of services being initialised were skipped)
=> fix(log): initialise before first use

web/ui/react-app/src/components/approvals/service.tsx, web/ui/react-app/src/components/generic/boolean-with-default.tsx, web/ui/react-app/src/components/generic/form-colour.tsx, web/ui/react-app/src/components/generic/form-select-creatable-sortable.tsx, web/ui/react-app/src/components/generic/form-select-creatable.tsx, web/ui/react-app/src/components/generic/form-select.tsx, web/ui/react-app/src/components/generic/form-text-area.tsx, web/ui/react-app/src/components/generic/form-text-with-button.tsx, web/ui/react-app/src/components/generic/form-text-with-preview.tsx, web/ui/react-app/src/components/generic/form-text.tsx, web/ui/react-app/src/components/generic/form.tsx, web/ui/react-app/src/components/modals/action-release/item.tsx, web/ui/react-app/src/components/modals/service-edit/dashboard.tsx, web/ui/react-app/src/components/modals/service-edit/deployed-version-manual.tsx, web/ui/react-app/src/components/modals/service-edit/version-with-link.tsx
fix(ui): improve deployed_version manual type input handling
- Add missing react-hook-form registration for version input
- Safely handle undefined service status in monitorData (new service)
Creating a new service and giving it a `manual` deployed_version caused an 'Uncaught TypeError'
---
feat(ui): add links to icon_url/web_url and visible lv/dv links on focus
- Create `FormTextWithButton` component for text fields with buttons
- Use this component for lv/dv `url` fields to keep links visible on focus
- Use this component to `icon_url` and `web_url` fields in dashboard
=> fix(ui): handle `manual` type deployed_version on new service

package.json, service/deployed_version/refresh.go, service/deployed_version/types/web/query.go, service/latest_version/refresh.go, service/latest_version/types/github/gets.go, service/latest_version/types/github/gets_test.go, service/latest_version/types/github/githubdata.go, service/latest_version/types/github/githubdata_test.go, service/latest_version/types/github/query.go, service/latest_version/types/github/query_test.go, service/latest_version/types/web/query.go, test/main.go, web/ui/package-lock.json, web/ui/react-app/package.json, web/ui/react-app/src/components/modals/service-edit/version-with-refresh.tsx, web/ui/react-app/src/utils/remove-empty-values.tsx
feat(latest_version): add pagination to GitHub release fetching - fixes #570 
- Enables fetching older releases, such as stable versions that appear on
later pages due to newer pre-releases being listed first.
fix(version-refresh): omit version from query keys
- Including the version in the query keys caused the initial refresh to be
skipped as the key changed after the version was fetched. Omitting the
version ensures the key remains consistent after the fetch.
fix(version-refresh): clear version errors after fetch
=> feat(latest_version): add pagination to GitHub release fetching

service/init.go, service/init_test.go, service/types.go, service/types_test.go, web/ui/react-app/src/components/modals/service-edit/version-with-refresh.tsx, web/ui/react-app/src/hooks/errors.tsx, web/ui/react-app/src/utils/errors.tsx
Version refreshes were having issues with `useQuery` query keys and so the error wasn't showing on the first fetch. This move to `useMutation` removes query keys shows the errors on the first fetch and makes more sense for the role of the component.
Also noticed in #573 that `service_name` was not being defaulted to `service_id` after creating/editing a service in the web ui.
=> fix(ui): show error on first version refresh failure

notify/shoutrrr/shoutrrr.go, notify/shoutrrr/shoutrrr_test.go
wasn't parsing environment variables when it built the params for sending messages
=> fix(notify): evaluate environment variables in params
